spring:

  application:
    name: webstore-auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        spring.json.trusted.packages: com.example.webstoreauthservice.model.dto.OrderDto

jwt:
  secret: AWqtLP+GFvnUBbpn1vbTpgmz8fwk6G14nQEVgJIBIVg=
  expiration: 86400000
  claim:
    uuid: userUuid

server:
  port: 8081
